export const USER_TOKEN_KEY = "USER_TOKEN_KEY";
export const USER_ID = "USER_ID";
export const FCM_TOKEN_KEY = "FCM_TOKEN_KEY";
export const SWIPES_PER_DAY_KEY = "SWIPES_PER_DAY_KEY";
export const SWIPES_REMAINING_KEY = "SWIPES_REMAINING_KEY";
export const SUPER_LIKES_REMAINING_KEY = "SUPER_LIKES_REMAINING_KEY";
