# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
     "react-native/scripts/react_native_pods.rb",
     {paths: [process.argv[1]]},
   )', __dir__]
).strip

platform :ios, '15.6'
prepare_react_native_project!



target 'parpple' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )
end

post_install do |installer|
  # 🔥 FIX: re-fetch react-native config here
  react_native_post_install(
    installer,
    '../node_modules/react-native',
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
    end
  end
end
