# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative '../node_modules/react-native-permissions/scripts/setup'


platform :ios, '15.5'

use_modular_headers!
prepare_react_native_project!

use_frameworks! :linkage => :static
setup_permissions([
  'LocationWhenInUse',
  'PhotoLibrary',
  'Camera',
])
target 'parpple' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  # AWS iOS SDK (used to obtain temporary credentials from Cognito Identity Pool)
  pod 'AWSCore'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSRekognition'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
